Docker
h2-open-source/ToxiChatBot pull request #12
Opened 2022-01-04 20:18 UTC by Dilden

This is an initial attempt at adding Docker support to the project to make standing up a development environment even faster.

2022-01-04 20:20 UTC, Dilden commented
This should also include a node container at some point. For now, I've followed [this blog post](https://faun.pub/managing-mongodb-on-docker-with-docker-compose-26bf8a0bbae3). [Here is the official documentation](https://hub.docker.com/_/mongo/) for the container images used.

2022-01-05 20:36 UTC, Dilden commented
This PR addresses #3

2022-01-11 22:51 UTC, Dilden commented
This request now includes everything needed to get the whole environment up and running within docker. No need to install MongoDB or even Node on your own machine.

2022-01-18 00:26 UTC, jimmyhogoboom requested changes
This is awesome! Once I managed to get `docker-compose` working, getting it running is EZ. Just found a couple little typos, But then this is good to go!

2022-01-18 00:26 UTC, jimmyhogoboom commented on README.md
> +5. Start [nodemon](https://nodemon.io/) to watch TypeScript files, buil on save, and restart the application.
"build on save"

2022-01-18 19:22 UTC, jimmyhogoboom approved these changes

2022-01-18 21:08 UTC, merged